{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Authentication API",
    "description" : "This is a simple API",
    "contact" : {
      "name" : "Kodez",
      "email" : "nusra0408@gmail.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0-oas3"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/myhub151/Cybermity_Authentication/1.0.0"
  } ],
  "security" : [ {
    "cybermity_auth" : [ ]
  } ],
  "tags" : [ {
    "name" : "Authentication",
    "description" : "Login With Username and password"
  } ],
  "paths" : {
    "/Sign-in" : {
      "post" : {
        "tags" : [ "Authentication" ],
        "summary" : "Login to the system",
        "description" : "Login with user email and password",
        "operationId" : "Login",
        "requestBody" : {
          "description" : "user email and password",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UserData"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Successfully loged-in"
          },
          "404" : {
            "description" : "Invalid Input"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "UserData" : {
        "type" : "object",
        "properties" : {
          "userEmail" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          }
        }
      }
    },
    "securitySchemes" : {
      "cybermity_auth" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "http://petstore.swagger.io/oauth/dialog",
            "tokenUrl" : "http://petstore.swagger.io/oauth/dialog",
            "scopes" : { }
          }
        }
      }
    }
  }
}