{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is for Cybermity Application",
    "version" : "1.0.0",
    "title" : "Authentication API",
    "contact" : {
      "name" : "Kodez",
      "email" : "nusra0408@gmail.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/myhub151/Cybermity_Authentication/1.0.0",
  "tags" : [ {
    "name" : "Authentication",
    "description" : "Login With Username and password"
  }, {
    "name" : "Token generating",
    "description" : "Retreive token from backend"
  } ],
  "schemes" : [ "https", "http" ],
  "security" : [ {
    "BasicAuth" : [ ]
  } ],
  "paths" : {
    "/sign-in" : {
      "post" : {
        "tags" : [ "Authentication" ],
        "summary" : "Login to the system",
        "description" : "Login with user email and password",
        "operationId" : "Login",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/xml", "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "Login details",
          "description" : "user email and password",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/UserData"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successfully loged-in"
          },
          "404" : {
            "description" : "Invalid Input"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/get-token/{userId}" : {
      "get" : {
        "tags" : [ "Token generating" ],
        "summary" : "Generate token to the system",
        "description" : "retreive token from the backend",
        "operationId" : "getToken",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "userId",
          "in" : "path",
          "description" : "the id of the user",
          "required" : true,
          "type" : "integer"
        } ],
        "responses" : {
          "200" : {
            "description" : "Success"
          },
          "404" : {
            "description" : "Invalid Input"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/get-jwt/{userId}" : {
      "get" : {
        "tags" : [ "Token generating" ],
        "summary" : "Generate jwt token to the system",
        "description" : "retreive jwt token from the backend",
        "operationId" : "getjwtToken",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "userId",
          "in" : "path",
          "description" : "the id of the user",
          "required" : true,
          "type" : "integer"
        } ],
        "responses" : {
          "200" : {
            "description" : "Success"
          },
          "404" : {
            "description" : "Invalid Input"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    }
  },
  "securityDefinitions" : {
    "BasicAuth" : {
      "type" : "basic"
    }
  },
  "definitions" : {
    "UserData" : {
      "type" : "object",
      "properties" : {
        "userEmail" : {
          "type" : "string"
        },
        "password" : {
          "type" : "string"
        }
      }
    }
  }
}